name: centipede
favicon: null
layout_spectrum: 0.29132322408258915
typography_spectrum: 0.3344825622625649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9000759983900934
  lightness: 0.07584983692504466
  saturation: 0.005512131378054619
  rhythmicContrast: 0.6765674473717809
purpose: []
